// questionsQPUC.js

const questionsCultureGenerale = [
    { question: "Quelle est la capitale de la France ?", reponse: "paris", points: 1 },
    { question: "Qui a écrit 'Les Misérables' ?", reponse: "victor hugo", points: 1 },
    { question: "De quelle couleur est le cercle au centre du drapeau japonais ?", reponse: "rouge", points: 1 },
    { question: "Dans quel pays peut-on visiter la ville de Venise ?", reponse: "italie", points: 1 },
    { question: "Quel est le plus grand océan du monde ?", reponse: "pacifique", points: 1 },
    { question: "Quel est le prénom de Einstein ?", reponse: "albert", points: 1 },
    { question: "Qui a peint la Joconde ?", reponse: "leonard de vinci", points: 1 },
    { question: "Quel est l'élément chimique dont le symbole est 'O' ?", reponse: "oxygene", points: 1 },
    { question: "Combien de continents y a-t-il sur Terre ?", reponse: "sept", points: 1 },
    { question: "Quel pays est connu comme le 'pays du Soleil Levant' ?", reponse: "japon", points: 1 },
    { question: "Qui a écrit 'Romeo et Juliette' ?", reponse: "william shakespeare", points: 1 },
    { question: "De quel pays Berlin est-elle la capitale ?", reponse: "allemagne", points: 1 },
    { question: "Quel métal est principalement utilisé pour fabriquer des canettes de boisson ?", reponse: "aluminium", points: 1 },
    { question: "Quelle est la plus grande planète du système solaire ?", reponse: "jupiter", points: 1 },
    { question: "Qui a peint 'La Nuit étoilée' ?", reponse: "vincent van gogh", points: 1 },
    { question: "Quel animal est le symbole national de l'Australie ?", reponse: "kangourou", points: 1 },
    { question: "Dans quel pays se trouve le Taj Mahal ?", reponse: "inde", points: 1 },
    { question: "Quel est le nom du président français pendant la Seconde Guerre mondiale ?", reponse: "charles de gaulle", points: 1 },
    { question: "Quelle est la capitale de l'Égypte ?", reponse: "le caire", points: 1 },
    { question: "Quel est le gaz majoritairement responsable de l'effet de serre ?", reponse: "dioxyde de carbone", points: 1 },
    { question: "Quel est le nom de la plus grande barrière de corail du monde ?", reponse: "grande barriere de corail", points: 1 },
    { question: "Qui est l'auteur de '1984' ?", reponse: "george orwell", points: 1 },
    { question: "Quel est le nom de la galaxie dans laquelle se trouve la Terre ?", reponse: "voie lactee", points: 1 },
    { question: "Quel est l'oiseau national des États-Unis ?", reponse: "aigle chauve", points: 1 },
    { question: "Quel pays est connu pour avoir construit la Grande Muraille ?", reponse: "chine", points: 1 },
    { question: "Qui a composé la musique de la 9ème symphonie ?", reponse: "ludwig van beethoven", points: 1 },
    { question: "Quelle ville est la capitale de la Russie ?", reponse: "moscou", points: 1 },
    { question: "Quel est le nom de la plus longue rivière en Europe ?", reponse: "volga", points: 1 },
    { question: "Qui a peint 'La Cène' ?", reponse: "leonard de vinci", points: 1 },
    { question: "Quelle est la planète la plus proche du Soleil ?", reponse: "mercure", points: 1 },

    // Questions de niveau 2
    { question: "Quelle ville est surnommée 'La ville éternelle' ?", reponse: "rome", points: 2 },
    { question: "Quel est le nom de la déesse grecque de la victoire ?", reponse: "nike", points: 2 },
    { question: "Quelle est la langue la plus parlée dans le monde ?", reponse: "chinois mandarin", points: 2 },
    { question: "Qui a écrit 'Le Vieil Homme et la Mer' ?", reponse: "ernest hemingway", points: 2 },
    { question: "Quel est le composant principal des étoiles ?", reponse: "hydrogene", points: 2 },
    { question: "Quel pays est connu comme le berceau de la démocratie ?", reponse: "grece", points: 2 },
    { question: "Quel est le plus grand désert du monde ?", reponse: "sahara", points: 2 },
    { question: "Quel compositeur est célèbre pour ses symphonies, notamment la 5ème et la 9ème ?", reponse: "ludwig van beethoven", points: 2 },
    { question: "Qui a écrit 'Le Prince' ?", reponse: "nicolas machiavel", points: 2 },
    { question: "Quel est le nom du satellite naturel de la Terre ?", reponse: "lune", points: 2 },
    { question: "Qui est l'auteur de 'À la recherche du temps perdu' ?", reponse: "marcel proust", points: 2 },
    { question: "Quel est le plus long fleuve du monde ?", reponse: "nil", points: 2 },
    { question: "En quelle année a commencé la Seconde Guerre mondiale ?", reponse: "1939", points: 2 },
    { question: "Quel est le nom du premier homme à avoir marché sur la Lune ?", reponse: "neil armstrong", points: 2 },
    { question: "Quel est le pays d'origine de la marque Samsung ?", reponse: "coree du sud", points: 2 },
    { question: "Quel est le plus petit pays du monde ?", reponse: "vatican", points: 2 },
    { question: "En quelle année la chute du mur de Berlin a-t-elle eu lieu ?", reponse: "1989", points: 2 },
    { question: "Quelle est la devise de l'Union européenne ?", reponse: "unite dans la diversite", points: 2 },
    { question: "Quel philosophe a écrit 'Critique de la raison pure' ?", reponse: "emmanuel kant", points: 2 },
    { question: "Quel élément chimique a pour symbole 'Au' ?", reponse: "or", points: 2 },
    { question: "Quelle est la capitale du Canada ?", reponse: "ottawa", points: 2 },
    { question: "Qui a écrit 'Les Fleurs du Mal' ?", reponse: "charles baudelaire", points: 2 },
    { question: "Dans quel pays se trouve le Machu Picchu ?", reponse: "perou", points: 2 },
    { question: "Quel philosophe a écrit 'L'État et la Révolution' ?", reponse: "vladimir lenine", points: 2 },
    { question: "Quel est le plus haut sommet d'Europe ?", reponse: "mont blanc", points: 2 },
    { question: "Qui est l'inventeur du téléphone ?", reponse: "alexander graham bell", points: 2 },
    { question: "Quel est le plus grand mammifère marin ?", reponse: "baleine bleue", points: 2 },
    { question: "Dans quel pays se trouve le Colisée ?", reponse: "italie", points: 2 },
    { question: "Quelle est la langue officielle de l'Égypte ?", reponse: "arabe", points: 2 },
    { question: "Qui est le dieu du tonnerre dans la mythologie nordique ?", reponse: "thor", points: 2 },

    // Questions de niveau 3
    { question: "Quelle est la capitale de la Mongolie ?", reponse: "oulan-bator", points: 3 },
    { question: "Qui a écrit 'La Divine Comédie' ?", reponse: "dante alighieri", points: 3 },
    { question: "Quel est le nom du plus long fleuve d'Afrique ?", reponse: "nil", points: 3 },
    { question: "Quelle ville était autrefois connue sous le nom de Byzance ?", reponse: "istanbul", points: 3 },
    { question: "Qui est le fondateur du bouddhisme ?", reponse: "siddhartha gautama", points: 3 },
    { question: "Quel est le composant principal de l'atmosphère de Mars ?", reponse: "dioxyde de carbone", points: 3 },
    { question: "Quelle est la langue la plus ancienne écrite encore utilisée de nos jours ?", reponse: "chinois", points: 3 },
    { question: "Qui a écrit 'Le Capital' ?", reponse: "karl marx", points: 3 },
    { question: "Quel est le nom du plus grand désert d'Asie ?", reponse: "gobi", points: 3 },
    { question: "Dans quel pays se trouve la ville sainte de La Mecque ?", reponse: "arabie saoudite", points: 3 },
    { question: "Quelle est la capitale de la Nouvelle-Zélande ?", reponse: "wellington", points: 3 },
    { question: "Qui a peint 'Guernica' ?", reponse: "pablo picasso", points: 3 },
    { question: "Quel est l'élément chimique dont le symbole est 'Fe' ?", reponse: "fer", points: 3 },
    { question: "Quelle est la plus profonde fosse océanique du monde ?", reponse: "fosse des mariannes", points: 3 },
    { question: "Qui est l'auteur de 'Don Quichotte' ?", reponse: "miguel de cervantes", points: 3 },
    { question: "Dans quel pays se trouve la ville de Petra, célèbre pour ses structures taillées dans la roche ?", reponse: "jordanie", points: 3 },
    { question: "Qui a découvert la loi de la gravitation universelle ?", reponse: "isaac newton", points: 3 },
    { question: "Quel pharaon a construit les grandes pyramides de Gizeh ?", reponse: "kheops", points: 3 },
    { question: "Quelle est la langue la plus ancienne encore parlée aujourd'hui ?", reponse: "tamoul", points: 3 },
    { question: "Qui était le dieu principal dans la mythologie nordique ?", reponse: "odin", points: 3 },
    { question: "Quelle est la capitale de l'Estonie ?", reponse: "tallinn", points: 3 },
    { question: "Qui a composé les Quatre Saisons ?", reponse: "antonio vivaldi", points: 3 },
    { question: "Quel est l'os le plus long du corps humain ?", reponse: "femur", points: 3 },
    { question: "Qui a écrit 'Guerre et Paix' ?", reponse: "leon tolstoi", points: 3 },
    { question: "Quelle est la théorie de l'évolution de Charles Darwin ?", reponse: "selection naturelle", points: 3 },
    { question: "Quel est le nom de la peinture murale réalisée par Michel-Ange dans la chapelle Sixtine ?", reponse: "le jugement dernier", points: 3 },
    { question: "Quel est le plus haut sommet du monde ?", reponse: "everest", points: 3 },
    { question: "Qui a découvert la pénicilline ?", reponse: "alexander fleming", points: 3 },
    { question: "Quel est le livre sacré de l'Islam ?", reponse: "coran", points: 3 },
    { question: "Dans quel pays se trouve le temple d'Angkor Vat ?", reponse: "cambodge", points: 3 },  
  ];
  
  module.exports = questionsCultureGenerale;
  