const questions = [
    { question: "Quelle est ma date de naissance ? (JJ/MM/AAAA)", reponse: "15/09/1991" },
    { question: "Quelle est ma couleur favoris ?", reponse: "Gris" },
    { question: "Quel est mon animal totem ?", reponse: "sanglier" },
    { question: "Quel est mon signe astrologique ?", reponse: "vierge" },
    { question: "Quel est mon plat favoris", reponse: "Porc au caramel" },
    { question: "Quel est mon dessert favoris", reponse: "foret noire" },
    { question: "Quel pays je reve de visiter", reponse: "japon" },
    { question: "Street food favoris", reponse: "kebab" },
    { question: "Quel est le nom de ma tortue", reponse: "Janine" },
    { question: "Quel est mon animal favoris", reponse: "chien" },
    { question: "Quel est mon film pas d'animation favoris", reponse: "12 hommes en colère" },
    { question: "Quel est mon film d'animation favoris", reponse: "Le voyage de Chihiro" },
    { question: "Quel est le pays le plus loin de la France ou je suis allé", reponse: "australie" },
    { question: "Je suis plutôt de gauche ou de droite", reponse: "gauche" },
    { question: "Quel est mon film Twilight favoris", reponse: "premier" },
    { question: "Mon manga favoris", reponse: "hunter x hunter"},
    { question: "Mon anime favoris", reponse: "jujutsu kaisen"},
    { question: "Mon jeu auquel je joue le plus", reponse: "isaac"},
    { question: "Le meilleur jeu du monde selon moi", reponse: "Outer Wilds"},
    { question: "Mon fruit favoris", reponse: "fraise"},
    { question: "Mon signe du zodiaque chinois", reponse: "chevre"},
    { question: "Mon style de musique favoris", reponse: "rap"},
    { question: "Mon rappeur favoris", reponse: "Kanye West"},
    { question: "Ma plus grande phobie", reponse: "profondeurs"},
    { question: "Ma recette que je fais le mieux", reponse: "Pâtes au bleu*"},
  ];

module.exports = questions;